config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.create(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class = "container mt-2">
  <div>
    <h1>All our flat 🏠 (<%= @flats.count %>)</h1>
    <h2><i class="fa-solid fa-square-plus"></i>   <%= link_to "Add yours!", new_flat_path %>   <i class="fa-solid fa-square-plus"></i></h2>
  </div>
  <% @flats.each do |flat| %>
    <div class = "mt-3 border rounded shadow-sm">
      <div class = "m-3">
        <h2><%= flat.name %></h2>
        <p><%= flat.address %></p>
        <p><i class="fa-solid fa-user"></i> <%= flat.number_of_guests %>    <i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %></p>
        <%= link_to "More info", flat %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div style =  "margin: 0 auto" class = "container row border">
  <div class = "d-flex justify-content-center">
    <div class = "col-8">
      <div class = "m-3 p-2 border rounded shadow-sm bg-light">
        <h2><%= @flat.name %></h2>
        <p><%= @flat.address %></p>
      </div>
      <div class = "m-3 p-2 border rounded shadow-sm bg-light">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
      <div class = "m-3 p-2 border rounded shadow-sm bg-light">
        <h3>Details</h3>
        <p><i class="fa-solid fa-user"></i> <%= @flat.number_of_guests %>    <i class="fa-solid fa-euro-sign"></i> <%= @flat.price_per_night %></p>
      </div>
    </div>
    <form class = "col-4">
      <p>Book this place!</p>
      <div class = "row">
        <label class = "col-sm-2 col-form-label" for="start"> From: </label>
        <div class = "col-sm-2">
          <input type="date" name="start" placeholder="dd-mm-yyyy">
        </div>
      </div>
      <div class = "row">
        <label class = "col-sm-2 col-form-label" for="End"> Until: </label>
        <div class = "col-sm-2">
          <input type="date" name="End" placeholder="dd-mm-yyyy" id = "End">
        </div>
      </div>
    </form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>